// lib/mock-data.js
// Mock data สำหรับ Development Phase 2
// จะถูกแทนที่ด้วย API calls จริงใน Phase 3

export const MOCK_TOURS = [
  {
    id: "tour-001",
    slug: "bangkok-culture-3d2n",
    title: "กรุงเทพฯ วัฒนธรรม 3 วัน 2 คืน",
    excerpt: "สัมผัสความงามของกรุงเทพฯ เมืองหลวงแห่งเทวดา ชมวัดวาอาราม ล่องเรือเจ้าพระยา ช้อปปิ้งตลาดสำเพ็ง",
    coverImage: "/images/tour-bangkok.jpg",
    price: 4990,
    priceOld: 5990,
    duration: 3,
    nights: 2,
    destinations: ["กรุงเทพมหานคร"],
    difficulty: "EASY",
    category: { name: "ทัวร์ในประเทศ", slug: "domestic" },
    tags: ["วัฒนธรรม", "ช้อปปิ้ง", "ล่องเรือ"],
    rating: 4.8,
    reviewCount: 128,
    featured: true,
  },
  {
    id: "tour-002",
    slug: "chiangmai-nature-4d3n",
    title: "เชียงใหม่ ธรรมชาติ 4 วัน 3 คืน",
    excerpt: "ผจญภัยในป่าเขาเชียงใหม่ ขี่ช้าง ดอยอินทนนท์ ตลาดอนุสาร วัดพระธาตุดอยสุเทพ",
    coverImage: "/images/tour-chiangmai.jpg",
    price: 7990,
    priceOld: null,
    duration: 4,
    nights: 3,
    destinations: ["เชียงใหม่"],
    difficulty: "MODERATE",
    category: { name: "ทัวร์ในประเทศ", slug: "domestic" },
    tags: ["ธรรมชาติ", "ช้าง", "ดอย"],
    rating: 4.9,
    reviewCount: 89,
    featured: true,
  },
  {
    id: "tour-003",
    slug: "krabi-island-5d4n",
    title: "กระบี่ เกาะสวรรค์ 5 วัน 4 คืน",
    excerpt: "สัมผัสความงามของทะเลกระบี่ เกาะพีพี ถ้ำพระนาง ทะเลแหวก ดำน้ำชมปะการัง",
    coverImage: "/images/tour-krabi.jpg",
    price: 12990,
    priceOld: 15990,
    duration: 5,
    nights: 4,
    destinations: ["กระบี่", "เกาะพีพี"],
    difficulty: "EASY",
    category: { name: "ทัวร์ทะเล", slug: "beach" },
    tags: ["ทะเล", "เกาะ", "ดำน้ำ"],
    rating: 4.7,
    reviewCount: 203,
    featured: true,
  },
  {
    id: "tour-004",
    slug: "phuket-luxury-3d2n",
    title: "ภูเก็ต หรูหรา 3 วัน 2 คืน",
    excerpt: "พักโรงแรมระดับ 5 ดาว ชายหาดป่าตอง ชมพระอาทิตย์ตก แหลมพรหมเทพ",
    coverImage: "/images/tour-krabi.jpg",
    price: 18990,
    priceOld: 22000,
    duration: 3,
    nights: 2,
    destinations: ["ภูเก็ต"],
    difficulty: "EASY",
    category: { name: "ทัวร์ระดับพรีเมียม", slug: "luxury" },
    tags: ["หรูหรา", "ทะเล", "โรงแรม 5 ดาว"],
    rating: 4.9,
    reviewCount: 67,
    featured: false,
  },
  {
    id: "tour-005",
    slug: "ayutthaya-history-2d1n",
    title: "อยุธยา มรดกโลก 2 วัน 1 คืน",
    excerpt: "ย้อนรอยประวัติศาสตร์อยุธยา เมืองหลวงเก่า ชมวัดเก่าแก่ ล่องเรือชมพระนครศรีอยุธยา",
    coverImage: "/images/tour-bangkok.jpg",
    price: 2990,
    priceOld: 3500,
    duration: 2,
    nights: 1,
    destinations: ["อยุธยา"],
    difficulty: "EASY",
    category: { name: "ทัวร์ประวัติศาสตร์", slug: "history" },
    tags: ["ประวัติศาสตร์", "มรดกโลก", "วัฒนธรรม"],
    rating: 4.6,
    reviewCount: 45,
    featured: false,
  },
  {
    id: "tour-006",
    slug: "northern-trek-7d6n",
    title: "ทริปเหนือ เดินป่า 7 วัน 6 คืน",
    excerpt: "ผจญภัยเดินป่าภาคเหนือ ชมดาวบนดอย แม่ฮ่องสอน ปาย ดอยแม่คลอง",
    coverImage: "/images/tour-chiangmai.jpg",
    price: 22990,
    priceOld: null,
    duration: 7,
    nights: 6,
    destinations: ["เชียงใหม่", "แม่ฮ่องสอน", "ปาย"],
    difficulty: "CHALLENGING",
    category: { name: "ทัวร์ผจญภัย", slug: "adventure" },
    tags: ["เดินป่า", "ผจญภัย", "ภาคเหนือ"],
    rating: 4.8,
    reviewCount: 32,
    featured: false,
  },
];

export const MOCK_TESTIMONIALS = [
  {
    id: 1,
    name: "คุณสมใจ ใจดี",
    avatar: null,
    location: "กรุงเทพมหานคร",
    rating: 5,
    comment: "บริการดีเยี่ยม ไกด์พูดภาษาไทยชัดเจน ให้ข้อมูลครบถ้วน ทริปเชียงใหม่สนุกมากๆ แนะนำเลยครับ",
    tourTitle: "เชียงใหม่ ธรรมชาติ 4 วัน 3 คืน",
  },
  {
    id: 2,
    name: "คุณมาลี รักเดินทาง",
    avatar: null,
    location: "เชียงใหม่",
    rating: 5,
    comment: "ประทับใจมากค่ะ โรงแรมที่จัดให้ดีมาก อาหารอร่อย และทีมงานดูแลทุกคนเป็นอย่างดี จะมาอีกแน่นอน",
    tourTitle: "กระบี่ เกาะสวรรค์ 5 วัน 4 คืน",
  },
  {
    id: 3,
    name: "คุณวิชัย สุขสันต์",
    avatar: null,
    location: "นครราชสีมา",
    rating: 5,
    comment: "คุ้มค่ามากครับ ราคาไม่แพง แต่ได้สถานที่ที่สวยงาม ไกด์มีความรู้เรื่องวัฒนธรรมไทยดีมาก",
    tourTitle: "กรุงเทพฯ วัฒนธรรม 3 วัน 2 คืน",
  },
];

export const MOCK_STATS = [
  { label: "นักท่องเที่ยวที่พึงพอใจ", value: "15,000+", suffix: "คน" },
  { label: "ปีแห่งประสบการณ์", value: "10+", suffix: "ปี" },
  { label: "แพ็คเกจทัวร์", value: "200+", suffix: "แพ็คเกจ" },
  { label: "คะแนนความพึงพอใจ", value: "4.9", suffix: "/5" },
];

export const MOCK_CATEGORIES = [
  { name: "ทัวร์ทะเล", slug: "beach", icon: "🏖️", count: 45 },
  { name: "ทัวร์ภูเขา", slug: "mountain", icon: "⛰️", count: 28 },
  { name: "ทัวร์วัฒนธรรม", slug: "culture", icon: "🏯", count: 32 },
  { name: "ทัวร์ผจญภัย", slug: "adventure", icon: "🧗", count: 18 },
  { name: "ทัวร์ระดับพรีเมียม", slug: "luxury", icon: "✨", count: 15 },
  { name: "ทัวร์ฮันนีมูน", slug: "honeymoon", icon: "💑", count: 22 },
];
